swagger: '2.0'
info:
  description: >-
    Current API provides access to AuthService, which is a part of SecureFiles
    project, which gives you powerfull tool to upload your files in completely
    secure mode and share it with people you trust to see this absolutely secret
    files.
  version: 1.0.2
  title: Statistic Service Service
  termsOfService: 'http://service-name-here/terms/'
  contact:
    email: apiteam@authservice.com
host: 'localhost:8989'
basePath: /v0
produces:
  - application/xml
  - application/json
tags:
  - name: Statistics
    description: Get statistics
schemes:
  - http
paths:
  /stat/size/{userId}:
    get:
      tags:
        - Statistics
      summary: Get size of all uploaded files for this user
      description: ''
      operationId: statSize
      parameters:
        - name: "userId"
          in: "path"
          description: "ID of user to get statistics for"
          required: true
          type: "string"
      responses:
        '200':
          description: successfull operation
          schema:
            type: string
        '400':
          description: Bad request
        default:
          description: invalid input
          schema:
            $ref: '#/definitions/Error'

definitions:
  Statistics:
    type: object
    required:
    - fileName
    - fileSize
    - mime
    - expirationTime
    properties:
      id:
        type: integer
        format: int64
      fileUploadDate:
        type: string
        format: date-time
      userId:
        type: integer
        format: int64
      operationName:
        type: string
      size:
        type: integer
        format: int64
    xml:
      name: FileMetadata

  Error:
    type: object
    properties:
      code:
        type: integer
        format: int32
      type:
        type: string
      message:
        type: string
    xml:
      name: Error